// Publication record. Edit here; the page renders from this array.
// selected: shown in the default "Selected" view (mirrored as static HTML in index.html).
const PUBLICATIONS = [
  {
    title: 'FutureWeaver: Planning Test-Time Compute for Multi-Agent Systems with Modularized Collaboration',
    authors: 'Dongwon Jung, Peng Shi, Muhao Chen, Yi Zhang',
    venue: 'COLM',
    year: 2026,
    selected: true,
  },
  {
    title: 'Log-Augmented Generation: Scaling Test-Time Reasoning with Reusable Computation',
    authors: 'Peter Baile Chen, Yi Zhang, Dan Roth, Samuel Madden, Jacob Andreas, Michael Cafarella',
    venue: 'ICLR',
    year: 2026,
    selected: true,
  },
  {
    title: 'IPR: Intelligent Prompt Routing with User-Controlled Quality-Cost Trade-offs',
    authors: 'Aosong Feng, Balasubramaniam Srinivasan, Yun Zhou, Zhichao Xu, Kang Zhou, Sheng Guan, Yueyan Chen, Xian Wu, Ninad Kulkarni, Yi Zhang, Zhengyuan Shen, Dmitriy Bespalov, Soumya Smruti Mishra, Yifei Teng, Darren Yow-Bang Wang, Haibo Ding, Lin Lee Cheong',
    venue: 'EMNLP',
    year: 2025,
  },
  {
    title: 'Can We Retrieve Everything All at Once? ARM: An Alignment-Oriented LLM-based Retrieval Method',
    authors: 'Peter Baile Chen, Yi Zhang, Michael Cafarella, Dan Roth',
    venue: 'ACL',
    year: 2025,
    selected: true,
  },
  {
    title: 'On Synthetic Data Strategies for Domain-Specific Generative Retrieval',
    authors: 'Haoyang Wen, Jiang Guo, Yi Zhang, Jiarong Jiang, Zhiguo Wang',
    venue: 'ACL',
    year: 2025,
    selected: true,
  },
  {
    title: 'Open Domain Question Answering with Conflicting Contexts',
    authors: 'Siyi Liu, Qiang Ning, Kishaloy Halder, Wei Xiao, Zheng Qi, Phu Mon Htut, Yi Zhang, Neha Anna John, Bonan Min, Yassine Benajiba, Dan Roth',
    venue: 'NAACL',
    year: 2025,
  },
  {
    title: 'Searching Data Lakes for Nested and Joined Data',
    authors: 'Yi Zhang, Peter Baile Chen, Zachary G. Ives',
    venue: 'VLDB',
    year: 2024,
  },
  {
    title: 'MDCR: A Dataset for Multi-Document Conditional Reasoning',
    authors: 'Peter Baile Chen, Yi Zhang, Chunwei Liu, Sejal Gupta, Yoon Kim, Michael Cafarella',
    venue: 'EMNLP Findings',
    year: 2024,
  },
  {
    title: 'Is Table Retrieval a Solved Problem? Exploring Join-Aware Multi-Table Retrieval',
    authors: 'Peter Baile Chen, Yi Zhang, Dan Roth',
    venue: 'ACL',
    year: 2024,
    award: 'Outstanding Paper — Towards Knowledgeable LMs @ ACL 2024',
    selected: true,
  },
  {
    title: 'Design Challenges for a Multi-Perspective Search Engine',
    authors: 'Sihao Chen, Siyi Liu, Xander Uyttendaele, Yi Zhang, William Bruno, Dan Roth',
    venue: 'NAACL',
    year: 2022,
  },
  {
    title: 'What is Your Article Based On? Inferring Fine-grained Provenance',
    authors: 'Yi Zhang, Zachary G. Ives, Dan Roth',
    venue: 'ACL',
    year: 2021,
  },
  {
    title: 'Learning to Decompose and Organize Complex Tasks',
    authors: 'Yi Zhang, Sujay Jauhar, Julia Kiseleva, Ryen White, Dan Roth',
    venue: 'NAACL',
    year: 2021,
    selected: true,
  },
  {
    title: '"Who Said It, and Why?" Provenance for Natural Language Claims',
    authors: 'Yi Zhang, Zachary G. Ives, Dan Roth',
    venue: 'ACL',
    year: 2020,
  },
  {
    title: 'Finding Related Tables in Data Lakes for Interactive Data Science',
    authors: 'Yi Zhang, Zachary G. Ives',
    venue: 'SIGMOD',
    year: 2020,
    selected: true,
  },
  {
    title: 'Juneau: Data Lake Management for Jupyter',
    authors: 'Yi Zhang, Zachary G. Ives',
    venue: 'VLDB',
    year: 2019,
    award: 'Best Demonstration Award',
    selected: true,
  },
  {
    title: 'Evidence-based Trustworthiness',
    authors: 'Yi Zhang, Zachary G. Ives, Dan Roth',
    venue: 'ACL',
    year: 2019,
  },
  {
    title: 'Dataset Relationship Management',
    authors: 'Zachary G. Ives, Yi Zhang, Soonbo Han, Nan Zheng',
    venue: 'CIDR',
    year: 2019,
  },
  {
    title: 'Entity Suggestion with Conceptual Explanation',
    authors: 'Yi Zhang, Yanghua Xiao, Seung-won Hwang, Haixun Wang, X. Sean Wang, Wei Wang',
    venue: 'IJCAI',
    year: 2017,
  },
  {
    title: 'Graph-based Wrong IsA Relation Detection in a Large-scale Lexical Taxonomy',
    authors: 'Jiaqing Liang, Yi Zhang, Yanghua Xiao, Seung-won Hwang, Haixun Wang',
    venue: 'AAAI',
    year: 2017,
  },
  {
    title: 'On the Transitivity of Hypernym-Hyponym Relations in Data-Driven Lexical Taxonomies',
    authors: 'Jiaqing Liang, Yi Zhang, Yanghua Xiao, Haixun Wang, Wei Wang, Pinpin Zhu',
    venue: 'AAAI',
    year: 2017,
  },
  {
    title: 'Probase+: Inferring Missing Links in Conceptual Taxonomies',
    authors: 'Jiaqing Liang, Yi Zhang, Yanghua Xiao, Haixun Wang, Wei Wang',
    venue: 'TKDE',
    year: 2016,
  },
  {
    title: 'Cross-lingual Type Inference',
    authors: 'Bo Xu, Yi Zhang, Jiaqing Liang, Yanghua Xiao, Seung-won Hwang, Wei Wang',
    venue: 'DASFAA',
    year: 2016,
  },
  {
    title: 'Learning Defining Features for Categories',
    authors: 'Bo Xu, Chenhao Xie, Yi Zhang, Yanghua Xiao, Haixun Wang, Wei Wang',
    venue: 'IJCAI',
    year: 2016,
  },
];
